## See the paper: Floating Point Calculations on a Quantum Annealer: Division and Matrix Inversion
### Section III Matrix Inversion as a QUBO Problem
Given $M\in R^{NxN}$ with $\det(M)\not=0$ and $Y\in R^{N}$, find $M^{-1}$ to solve the linear equation:
$ M\cdot x = Y \to x=M^{-1}\cdot Y$

In [1]:
import numpy as np
from linear_solver_float import LinearSolverFloat

In [2]:
# set floating point accuracy 
R = 5

In [3]:
M = np.array([[-4,6,1],
              [8,-11,-2],
              [-3,4,1]]) # Test 2(f)

Y = np.array([0.75,-1.25,0.25])

M_inv = np.linalg.inv(M)

In [4]:
M_inv.dot(Y)

array([ 0.  ,  0.25, -0.75])

In [5]:
num_reads = 1000
min_occurrence = 2
lsf = LinearSolverFloat(M,Y,R=R,num_reads=num_reads, min_occurrence = min_occurrence)
sampleset = lsf.sample()
sampleset.to_pandas_dataframe()

0  1  2  3  4  5  6  7  8  9  10  11  12  13  14  chain_break_fraction  \
0    0  0  0  0  0  0  0  0  1  1   0   1   1   1   1              0.000000   
1    0  0  0  0  0  0  0  0  1  1   0   1   1   1   0              0.000000   
2    0  0  0  0  0  0  0  0  1  1   0   1   1   0   1              0.000000   
3    0  0  0  0  0  0  0  0  1  1   0   1   1   0   0              0.000000   
4    0  0  0  0  0  0  0  0  1  0   0   1   1   1   1              0.000000   
..  .. .. .. .. .. .. .. .. .. ..  ..  ..  ..  ..  ..                   ...   
477  0  0  1  1  0  0  0  1  0  0   0   1   0   0   0              0.000000   
478  0  0  1  1  1  0  0  1  0  0   0   1   0   1   0              0.000000   
479  0  0  0  0  0  0  0  0  0  1   0   1   1   0   0              0.066667   
480  0  0  0  1  0  0  0  1  1  1   0   1   0   1   0              0.066667   
481  0  1  0  1  0  0  0  1  0  1   0   1   1   0   1              0.000000   

        energy  num_occurrences  
0    -64.93750                1  
1    -63.31250                3  
2    -61.87500                1  
3    -60.06250                1  
4    -58.18750                1  
..         ...              ...  
477   90.06250                2  
478  100.46875                1  
479  -48.96875                1  
480   -6.18750                1  
481  218.43750                1  

[482 rows x 18 columns]

In [9]:
solutions = lsf.getSolutions(10)
list(solutions)

[(array([-1.   , -0.875,  0.75 ]), -54.21875, 10),
 (array([-1.   , -0.375,  0.75 ]), -29.15625, 11),
 (array([-0.75 , -0.875,  0.75 ]), -21.15625, 10),
 (array([-0.75 , -0.375,  0.75 ]), -11.59375, 11),
 (array([-0.75 , -0.375,  0.375]), -8.6875, 10),
 (array([-0.75 , -0.375,  0.25 ]), -6.96875, 12),
 (array([-0.625, -0.375,  0.75 ]), -2.8125, 11)]

In [11]:
M = np.array([[6.1795,11.8207,2.0583],
              [15.673,-7.56717,-3.852],
              [-5.6457,7.96872,15.9418]]) #Test 2(g)

Y = np.array([1.4114,0.9972,9.9643])

M_inv = np.linalg.inv(M)
M_inv.dot(Y)

array([ 0.19364225, -0.1123896 ,  0.7497991 ])

In [12]:
M.dot(np.array([0,0.25,-0.75]))

array([ 1.41145  ,  0.9972075, -9.96417  ])

In [13]:
lsf = LinearSolverFloat(M,Y,R=R,num_reads=num_reads, min_occurrence = min_occurrence)
sampleset = lsf.sample()
sampleset.to_pandas_dataframe()

0  1  2  3  4  5  6  7  8  9  10  11  12  13  14  chain_break_fraction  \
0    0  0  1  1  1  0  0  1  1  1   0   1   1   1   1              0.000000   
1    0  0  0  1  1  0  0  1  1  1   0   1   1   1   1              0.000000   
2    0  0  1  1  0  0  0  1  1  1   0   1   1   1   1              0.000000   
3    0  0  1  0  1  0  0  1  1  1   0   1   1   1   1              0.000000   
4    0  0  0  1  0  0  0  1  1  1   0   1   1   1   1              0.000000   
..  .. .. .. .. .. .. .. .. .. ..  ..  ..  ..  ..  ..                   ...   
338  0  0  0  1  0  0  0  1  1  1   0   1   0   1   0              0.066667   
339  0  1  0  1  0  0  1  0  0  0   0   0   1   1   0              0.000000   
340  0  0  1  0  0  0  0  1  0  1   0   1   1   1   1              0.066667   
341  0  0  1  1  1  0  0  1  0  1   0   1   0   1   1              0.066667   
342  0  0  0  0  1  0  1  0  0  1   0   1   0   1   0              0.066667   

          energy  num_occurrences  
0   -1011.012968               10  
1   -1003.794401               39  
2    -994.409745               15  
3    -987.672243                4  
4    -967.459736               23  
..           ...              ...  
338  -827.857087                1  
339  -256.869413                1  
340  -888.263166                1  
341  -776.226844                1  
342  -644.308165                1  

[343 rows x 18 columns]

In [14]:
list(lsf.getSolutions(10))

[(array([-0.125, -0.125,  0.875]), -1011.0129683447628, 10),
 (array([-0.625, -0.125,  0.875]), -1003.7944013976373, 39),
 (array([-0.25 , -0.125,  0.875]), -994.4097448389186, 15),
 (array([-0.75 , -0.125,  0.875]), -967.4597355330436, 23),
 (array([-0.625, -0.125,  0.75 ]), -966.8926133610128, 30),
 (array([-0.625, -0.25 ,  0.875]), -964.6688939188186, 13),
 (array([-0.25 , -0.125,  0.75 ]), -951.0553434549499, 11),
 (array([-0.375, -0.125,  0.75 ]), -946.4687122442626, 10),
 (array([-0.625, -0.375,  0.875]), -933.6837460880408, 26),
 (array([-0.75 , -0.125,  0.75 ]), -932.7088186121998, 26),
 (array([-0.75 , -0.25 ,  0.875]), -929.7489662145997, 10),
 (array([-0.125, -0.375,  0.875]), -929.5844077521658, 17),
 (array([-0.625, -0.25 ,  0.75 ]), -924.9465585986625, 11),
 (array([-0.25 , -0.375,  0.875]), -915.8106605670716, 16),
 (array([-0.75 , -0.375,  0.875]), -900.1785565441967, 32),
 (array([-0.625, -0.375,  0.75 ]), -891.1408634843535, 26),
 (array([-0.25 , -0.375,  0.75 ]), -86